// Configuração centralizada do layout do DRE e grupos de contas
// Gerado automaticamente a partir de js/script.js em 2025-12-23
(function(){
    window.DreConfig = window.DreConfig || {};
    window.DreConfig.dreDeptLayout = [
        { type: 'account', code: '3010', description: 'Consultant fees external' },
        { type: 'account', code: '3556', description: 'Consultant fees within own Business Area' },
        { type: 'account', code: '3557', description: 'Consultant fees to other Business Area' },
        { type: 'account', code: '3015', description: 'Write- up/down of fees' },
        { type: 'account', code: '3095', description: 'Provision not invoiced WIP' },
        { type: 'account', code: '3019', description: 'Fee other dep. within same comp.' },
        { type: 'account', code: '3018', description: 'Costs other dep. within same comp.' },
        { type: 'account', code: '3030', description: 'Subcontractor fees' },
        { type: 'account', code: '3204', description: 'Tax on revenue (Dynamic)' },
        { type: 'total', description: 'Total Revenue', bg: 'bg-yellow-100', id: 'total_revenue' },
        { type: 'account', code: '3413', description: 'Computers within projects' },
        { type: 'account', code: '3040', description: 'Travel expenses, outlay' },
        { type: 'account', code: '3050', description: 'Recharged expenses' },
        { type: 'account', code: '3110', description: 'Training' },
        { type: 'account', code: '3521', description: 'Sales of computers' },
        { type: 'account', code: '3910', description: 'Rents' },
        { type: 'account', code: '3510', description: 'Machinery fees' },
        { type: 'account', code: '32101', description: 'Licences' },
        { type: 'account', code: '3960', description: 'Exchange profit from business' },
        { type: 'account', code: '3973', description: 'Capital gains on fixed assets' },
        { type: 'account', code: '3900', description: 'Other income' },
        { type: 'total', description: 'Total Other Income', bg: 'bg-yellow-100', id: 'total_other_income' },
        { type: 'calculation', description: 'TOTAL INCOME', bg: 'bg-green-100', formula: 'total_revenue + total_other_income', id: 'total_income' },
        { type: 'header', description: 'Production costs' },
        { type: 'account', code: '7210', description: 'Salary consultants' },
        { type: 'account', code: '7200', description: 'Social Security' },
        { type: 'account', code: '7500', description: 'Statutory and Social Security contributions' },
        { type: 'account', code: '74001', description: 'Other personnel costs, consultants' },
        { type: 'account', code: '4619', description: 'Subcontractors from group comp.' },
        { type: 'account', code: '4110', description: 'Subcontractors' },
        { type: 'account', code: '4200', description: 'Machinery costs' },
        { type: 'account', code: '4040', description: 'Licence costs' },
        { type: 'account', code: '4211', description: 'Costs for computers in projects' },
        { type: 'account', code: '4550', description: 'Outlay/expenses projects' },
        { type: 'account', code: '4670', description: 'Material cost to customers' },
        { type: 'account', code: '4630', description: 'Computer software' },
        { type: 'account', code: '4223', description: 'Operating costs test' },
        { type: 'account', code: '4185', description: 'Education/training costs' },
        { type: 'account', code: '6624', description: 'Microsoft Licence' },
        { type: 'account', code: '4022', description: 'Cost of computers for sale' },
        { type: 'account', code: '4730', description: 'Other production costs' },
        { type: 'total', description: 'Total production costs', bg: 'bg-yellow-100', id: 'total_prod_costs' },
        { type: 'calculation', description: 'GROSS PROFIT', bg: 'bg-green-100', formula: 'total_income + total_prod_costs', id: 'gross_profit' },
        { type: 'account', code: '7110', description: 'Salary administration' },
        { type: 'account', code: '7199', description: 'Manager bonus' },
        { type: 'account', code: '7002', description: 'Salary salesmen' },
        { type: 'account', code: '7003', description: 'Salary leaders' },
        { type: 'account', code: '7004', description: 'Social Security' },
        { type: 'account', code: '7400', description: 'Other personnel costs' },
        { type: 'account', code: '5010', description: 'Office rental costs' },
        { type: 'account', code: '6110', description: 'Office expenses' },
        { type: 'account', code: '6300', description: 'Insurance and other riskrelated costs' },
        { type: 'account', code: '6500', description: 'Consultants and external services' },
        { type: 'account', code: '6200', description: 'Communication' },
        { type: 'account', code: '7615', description: 'Vehicle costs' },
        { type: 'account', code: '5900', description: 'Sales and marketing costs' },
        { type: 'account', code: '6354', description: 'Provision doubtful debts' },
        { type: 'account', code: '6352', description: 'Reserve high risk debts' },
        { type: 'account', code: '7960', description: 'Exchange loss from business' },
        { type: 'account', code: '6990', description: 'Other costs' },
        { type: 'account', code: '6998', description: 'Reversal One-off costs' },
        { type: 'account', code: '6999', description: 'One-off costs' },
        { type: 'account', code: '7973', description: 'Capital losses on fixed assets' },
        { type: 'total', description: 'Total administration costs', bg: 'bg-yellow-100', id: 'total_admin_costs' },
        { type: 'header', description: 'Depreciation' },
        { type: 'account', code: '7860', description: 'Depreciation intangible assets' },
        { type: 'account', code: '7850', description: 'Depreciation tangible assets' },
        { type: 'account', code: '7840', description: 'Depreciation intangible assets' },
        { type: 'account', code: '7830', description: 'Depreciation tangible assets' },
        { type: 'total', description: 'Total depreciation', bg: 'bg-yellow-100', id: 'total_depreciation' },
        { type: 'calculation', description: 'PROFIT BEFORE SaS', bg: 'bg-green-100', formula: 'gross_profit + total_admin_costs + total_depreciation', id: 'profit_before_sas' },
        { type: 'account', code: '6430', description: 'Management fee Semcon AB' },
        { type: 'account', code: '7981', description: 'Shared Service fee' },
        { type: 'account', code: '6435', description: 'Management fee Reduciton' },
        { type: 'account', code: '6436', description: 'Internal Business Area OH' },
        { type: 'account', code: '6437', description: 'Internal Region OH' },
        { type: 'account', code: '7994', description: 'Other management fees' },
        { type: 'total', description: 'Total SaS', bg: 'bg-yellow-100', id: 'total_sas' },
        { type: 'calculation', description: 'EBIT', bg: 'bg-green-100', formula: 'profit_before_sas + total_sas', id: 'ebit' },
        { type: 'account', code: '8010', description: 'Dividend from group companies' },
        { type: 'account', code: '8022', description: 'Result from sale of group companies' },
        { type: 'account', code: '8300', description: 'Interest income' },
        { type: 'account', code: '8360', description: 'Interest income, group companies' },
        { type: 'account', code: '8331', description: 'Exchange profit from financing' },
        { type: 'account', code: '8390', description: 'Other financial income' },
        { type: 'total', description: 'Total financial income', bg: 'bg-yellow-100', id: 'total_fin_income' },
        { type: 'account', code: '8072', description: 'Write-down of assets in group companies' },
        { type: 'account', code: '8400', description: 'Interest expenses' },
        { type: 'account', code: '8412', description: 'Interest expenses pension obligations' },
        { type: 'account', code: '8460', description: 'Interest expenses, group companies' },
        { type: 'account', code: '8436', description: 'Exchange loss from financing' },
        { type: 'account', code: '8490', description: 'Other financial expenses' },
        { type: 'total', description: 'Total financial expenses', bg: 'bg-yellow-100', id: 'total_fin_expenses' },
        { type: 'calculation', description: 'Finance net', bg: 'bg-green-100', formula: 'total_fin_income + total_fin_expenses', id: 'finance_net' },
        // { type: 'calculation', description: 'PROFIT AFTER FINANCIAL ITEMS', bg: 'bg-green-100', formula: 'ebit + finance_net', id: 'profit_after_fin' },
        { type: 'account', code: '8893', description: 'Contribution from/to group companies' },
        { type: 'account', code: '8820', description: 'Centrally approved items Semcon Operative fee' },
        { type: 'account', code: '8821', description: 'Centrally approved items Internal Business fee' },
        { type: 'account', code: '8828', description: 'Centrally approved items Legal Service fee' },
        { type: 'account', code: '8829', description: 'Centrally approved items Other' },
        { type: 'account', code: '8890', description: 'Other appropriations' },
        { type: 'total', description: 'Total appropriations', bg: 'bg-yellow-100', id: 'total_appropriations' },
        // { type: 'calculation', description: 'PROFIT BEFORE TAXES', bg: 'bg-green-100', formula: 'profit_after_fin + total_appropriations', id: 'profit_before_taxes' },
        { type: 'account', code: '8910', description: 'Current tax' },
        { type: 'account', code: '8935', description: 'WHT (Whithold tax)' },
        { type: 'account', code: '8940', description: 'Deferred tax' },
        { type: 'account', code: '8980', description: 'Other tax' },
        { type: 'total', description: 'Total tax', bg: 'bg-yellow-100', id: 'total_tax' },
        { type: 'calculation', description: 'Net profit or loss for the year', bg: 'bg-green-100', formula: 'ebit + finance_net + total_appropriations + total_tax', id: 'net_profit' },
        { type: 'header', description: 'ASSETS', bg: 'bg-blue-100' },
        { type: 'header', description: 'Fixed assets' },
        { type: 'header', description: 'Intangible assets' },
        { type: 'account', code: '1070', description: 'Goodwill' },
        { type: 'account', code: '1040', description: 'Other intangible assets' },
        { type: 'total', description: 'Total intangible assets', bg: 'bg-yellow-100', id: 'total_intangible' },
        { type: 'header', description: 'Tangible assets' },
        { type: 'account', code: '1110', description: 'Buildings and land' },
        { type: 'account', code: '1230', description: 'Plant and machinery' },
        { type: 'account', code: '1210', description: 'Equipment' },
        { type: 'account', code: '1220', description: 'Computers' },
        { type: 'total', description: 'Total tangible assets', bg: 'bg-yellow-100', id: 'total_tangible' },
        { type: 'header', description: 'Financial assets' },
        { type: 'account', code: '1312', description: 'Shares in group companies' },
        { type: 'account', code: '1315', description: 'Shares in associated companies' },
        { type: 'account', code: '1370', description: 'Deferred tax assets' },
        { type: 'account', code: '1360', description: 'Long-term receivables group companies' },
        { type: 'account', code: '1388', description: 'Other financial assets' },
        { type: 'total', description: 'Total financial assets', bg: 'bg-yellow-100', id: 'total_financial_assets' },
        { type: 'calculation', description: 'Total fixed assets', bg: 'bg-yellow-100', formula: 'total_intangible + total_tangible + total_financial_assets', id: 'total_fixed_assets' },
        { type: 'header', description: 'Current assets' },
        { type: 'account', code: '1510', description: 'Accounts receivable, external' },
        { type: 'account', code: '1560', description: 'Accounts receivable, group companies' },
        { type: 'account', code: '1565', description: 'Accounts receivable, Ratos group companies' },
        { type: 'account', code: '1400', description: 'Inventories' },
        { type: 'account', code: '1470', description: 'Work in progress' },
        { type: 'account', code: '1640', description: 'Current tax receivable' },
        { type: 'account', code: '1600', description: 'Other current receivables, employees' },
        { type: 'account', code: '1689', description: 'Other current receivables, external' },
        { type: 'account', code: '1660', description: 'Other current receivables, group companies' },
        { type: 'account', code: '1790', description: 'Prepaid expenses and accrued income' },
        { type: 'total', description: 'Total current assets excl. cash', bg: 'bg-yellow-100', id: 'total_current_excl_cash' },
        { type: 'account', code: '1960', description: 'Cash pool receivables, group companies' },
        { type: 'account', code: '1800', description: 'Short-term financial investments' },
        { type: 'account', code: '1930', description: 'Cash and bank' },
        { type: 'total', description: 'Total cash and bank equivalent', bg: 'bg-yellow-100', id: 'total_cash_bank' },
        { type: 'calculation', description: 'Total current assets', bg: 'bg-yellow-100', formula: 'total_current_excl_cash + total_cash_bank', id: 'total_current_assets' },
        { type: 'calculation', description: 'TOTAL ASSETS', bg: 'bg-green-100', formula: 'total_fixed_assets + total_current_assets', id: 'total_assets' },
        { type: 'header', description: 'SHAREHOLDERS\' EQUITY AND LIABILITIES', bg: 'bg-blue-100' },
        { type: 'header', description: 'Shareholders\' equity' },
        { type: 'header', description: 'Restricted equity' },
        { type: 'account', code: '2081', description: 'Share capital' },
        { type: 'account', code: '2086', description: 'Restricted reserves' },
        { type: 'header', description: 'Non-restricted equity' },
        { type: 'account', code: '2090', description: 'Profit brought forward' },
        { type: 'account', code: '2099', description: 'Net profit or loss for the year' },
        { type: 'account', code: '2200', description: 'Minority interest' },
        { type: 'total', description: 'Total shareholders\' equity', bg: 'bg-yellow-100', id: 'total_equity' },
        { type: 'account', code: '2190', description: 'Untaxed reserves' },
        { type: 'total', description: 'Total untaxed reserves', bg: 'bg-yellow-100', id: 'total_untaxed_reserves' },
        { type: 'header', description: 'Long-term liabilities' },
        { type: 'account', code: '2520', description: 'Deferred tax liabilities' },
        { type: 'account', code: '2270', description: 'Pension obligations' },
        { type: 'account', code: '2280', description: 'Other long-term provisions' },
        { type: 'account', code: '2352', description: 'Other long-term interest-bearing liabilities' },
        { type: 'account', code: '2390', description: 'Other long-term non interest-bearing liabilities' },
        { type: 'account', code: '2360', description: 'Other long-term liabilities, group companies' },
        { type: 'total', description: 'Total long-term liabilities', bg: 'bg-yellow-100', id: 'total_long_term_liab' },
        { type: 'header', description: 'Current liabilities' },
        { type: 'account', code: '2843', description: 'Cash pool liabilities, group companies' },
        { type: 'account', code: '2842', description: 'Overdraft facilities, external' },
        { type: 'account', code: '2841', description: 'Other current interest-bearing liabilities' },
        { type: 'account', code: '2440', description: 'Accounts payable, external' },
        { type: 'account', code: '2460', description: 'Accounts payable, group companies' },
        { type: 'account', code: '2510', description: 'Current tax liabilities' },
        { type: 'account', code: '2420', description: 'Advance payments from customers' },
        { type: 'account', code: '2700', description: 'Other current liabilities, employees' },
        { type: 'account', code: '2890', description: 'Other current liabilities, external' },
        { type: 'account', code: '2840', description: 'Loans' },
        { type: 'account', code: '2860', description: 'Other current liabilities, group companies' },
        { type: 'account', code: '2290', description: 'Other current provisions' },
        { type: 'account', code: '2902', description: 'Accrued expenses, employees & subcontractors' },
        { type: 'account', code: '2990', description: 'Accrued expenses and prepaid income' },
        { type: 'total', description: 'Total current liabilities', bg: 'bg-yellow-100', id: 'total_current_liab' },
        { type: 'calculation', description: 'TOTAL SHAREHOLDERS\' EQUITY AND LIABILITIES', bg: 'bg-blue-200', formula: 'total_equity + total_untaxed_reserves + total_long_term_liab + total_current_liab', id: 'total_equity_liab' }
    ];

    window.DreConfig.accountGroups = {
        custoAccounts: [2925, 2933, 2941, 2950, 2968, 2976, 2984, 2992, 3000, 3018, 3034, 3042, 3069, 3077, 3085, 3093, 3107, 3115, 3123, 3131, 3140, 3158, 3824, 3832, 11446, 11452, 3166, 24118, 24131, 17621],
        depreciacaoAccounts: [2623, 2631, 2331, 17711],
        pessoalAccounts: [2011, 2020, 2038, 2046, 2054, 2062, 2070, 2089, 2119, 2860, 2097, 2100, 2879, 2135, 2143, 2151, 2160, 2178, 2186, 2194, 2208, 2216, 3816, 3948, 11423, 11430, 2232, 24124, 24147],
        aluguelAccounts: [],
        viagensAccounts: [2305, 2313, 2321, 2330, 2348, 2356, 2364, 2372, 3506],
        deductionAccounts: [1945, 1953, 1961, 3212],
        diversasAccounts: [2380, 2399, 2402, 2410, 2429, 2437, 2445, 2453, 2461, 2470, 2488, 2496, 2500, 2518, 2526, 2534, 2550, 3514, 4146, 2542, 29624, 14581],
        servicosProfissionaisAccounts: [2569, 2577, 2585, 2593, 2607, 2615, 2887, 3620, 3590, 3581, 3522, 3530, 16455, 16573],
        taxasAccounts: [2640, 2658, 2666, 11558, 11564, 11571, 11587, 11676, 11742, 23001, 11759],
        outrasAdmAccounts: [2674, 2682, 2690],
        outrasPosAccounts: [],
        posEbitdaAccounts: [2704, 2720, 2739, 2747, 2771, 2780, 2798, 2801, 2810, 4120, 3867, 3875, 2895, 2909, 16248, 16254, 2844],
        managementFeeAccounts: [9999]
    };
})();
